create table if not exists public.quiet_corner_progress (
  id bigint generated by default as identity primary key,
  student_id bigint not null,
  activity_id text not null,
  progress jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  unique (student_id, activity_id)
);

alter table public.quiet_corner_progress enable row level security;

drop policy if exists "quiet corner public read" on public.quiet_corner_progress;
create policy "quiet corner public read"
on public.quiet_corner_progress
for select
to anon, authenticated
using (true);

drop policy if exists "quiet corner public insert" on public.quiet_corner_progress;
create policy "quiet corner public insert"
on public.quiet_corner_progress
for insert
to anon, authenticated
with check (true);

drop policy if exists "quiet corner public update" on public.quiet_corner_progress;
create policy "quiet corner public update"
on public.quiet_corner_progress
for update
to anon, authenticated
using (true)
with check (true);
