-- QUIET CORNER — SHARED SUPABASE SETUP
-- Run this once in the Supabase SQL Editor.

create table if not exists public.quiet_corner_progress (
  id bigint generated by default as identity primary key,
  student_id bigint not null,
  activity_id text not null,
  progress jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  unique (student_id, activity_id)
);

grant select on public.students to anon;
grant select, insert, update on public.quiet_corner_progress to anon;

alter table public.students enable row level security;
alter table public.quiet_corner_progress enable row level security;

drop policy if exists "quiet corner read active students" on public.students;
create policy "quiet corner read active students"
on public.students for select to anon
using (active = true);

drop policy if exists "quiet corner read progress" on public.quiet_corner_progress;
create policy "quiet corner read progress"
on public.quiet_corner_progress for select to anon
using (true);

drop policy if exists "quiet corner insert progress" on public.quiet_corner_progress;
create policy "quiet corner insert progress"
on public.quiet_corner_progress for insert to anon
with check (true);

drop policy if exists "quiet corner update progress" on public.quiet_corner_progress;
create policy "quiet corner update progress"
on public.quiet_corner_progress for update to anon
using (true)
with check (true);
